//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tennis4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitionEnrollment
    {
        public int ID { get; set; }
        public int PlayerID { get; set; }
        public int CompetitionRowID { get; set; }
    
        public virtual CompetitionRow CompetitionRow { get; set; }
        public virtual Player Player { get; set; }
    }
}
