//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tennis4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitionRow
    {
        public CompetitionRow()
        {
            this.CompetitionEnrollment = new HashSet<CompetitionEnrollment>();
        }
    
        public int ID { get; set; }
        public int RowName { get; set; }
        public int Capacity { get; set; }
        public int CompetitionID { get; set; }
    
        public virtual Competition Competition { get; set; }
        public virtual ICollection<CompetitionEnrollment> CompetitionEnrollment { get; set; }
    }
}
