//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tennis4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.CompetitionEnrollment = new HashSet<CompetitionEnrollment>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DayOfBirth { get; set; }
        public string TelephoneNumber { get; set; }
    
        public virtual ICollection<CompetitionEnrollment> CompetitionEnrollment { get; set; }
    }
}
